import type { ProjectsDataState } from '@/types/projects'

export const PROJECT_SEED: ProjectsDataState = {
  projects: [
    {
      id: 'p1',
      workspaceId: 'ws1',
      name: 'Rediseño App Móvil',
      description: 'Modernización completa de la experiencia móvil para clientes enterprise.',
      client: 'Acme Corp',
      responsibleId: 'u1',
      priority: 'alta',
      status: 'active',
      category: 'Producto',
      tags: ['mobile', 'ux', 'q1-2026'],
      startDate: '2026-01-10',
      dueDate: '2026-04-30',
      budget: 45000,
      currency: 'COP',
      profitabilityTarget: 25,
      boardId: 'b1',
      createdBy: 'u1',
      createdAt: '2026-01-10T10:00:00',
      updatedAt: '2026-02-20T14:00:00',
    },
    {
      id: 'p2',
      workspaceId: 'ws1',
      name: 'Portal de Clientes B2B',
      description: 'Nuevo portal self-service para gestión de pedidos y facturación.',
      client: 'Nova Industries',
      responsibleId: 'u2',
      priority: 'media',
      status: 'planning',
      category: 'Desarrollo',
      tags: ['web', 'b2b'],
      startDate: '2026-03-01',
      dueDate: '2026-08-15',
      budget: 78000,
      currency: 'COP',
      profitabilityTarget: 30,
      boardId: null,
      createdBy: 'u1',
      createdAt: '2026-02-01T09:00:00',
      updatedAt: '2026-02-15T11:00:00',
    },
  ],
  tasks: [
    {
      id: 'pt1',
      projectId: 'p1',
      title: 'Auditoría UX actual',
      description: 'Revisar flujos críticos y puntos de fricción.',
      status: 'done',
      priority: 'alta',
      assigneeIds: ['u3'],
      startDate: '2026-01-10',
      dueDate: '2026-01-25',
      completedAt: '2026-01-24T16:00:00',
      position: 0,
      kanbanColumn: 'done',
      boardCardId: 'c1',
      boardId: 'b1',
      attachments: [],
      estimateHours: null,
      loggedMinutes: 0,
      createdBy: 'u1',
      createdAt: '2026-01-10T10:00:00',
      updatedAt: '2026-01-24T16:00:00',
    },
    {
      id: 'pt2',
      projectId: 'p1',
      title: 'Sistema de diseño v2',
      description: 'Tokens, componentes y guía de estilos.',
      status: 'in_progress',
      priority: 'alta',
      assigneeIds: ['u2', 'u3'],
      startDate: '2026-01-26',
      dueDate: '2026-02-28',
      completedAt: null,
      position: 1,
      kanbanColumn: 'in_progress',
      boardCardId: null,
      boardId: null,
      attachments: [],
      estimateHours: null,
      loggedMinutes: 0,
      createdBy: 'u1',
      createdAt: '2026-01-26T09:00:00',
      updatedAt: '2026-02-18T10:00:00',
    },
    {
      id: 'pt3',
      projectId: 'p1',
      title: 'Prototipos navegación',
      description: 'Flujos principales en Figma.',
      status: 'todo',
      priority: 'media',
      assigneeIds: ['u4'],
      startDate: '2026-02-15',
      dueDate: '2026-03-10',
      completedAt: null,
      position: 2,
      kanbanColumn: 'todo',
      boardCardId: null,
      boardId: null,
      attachments: [],
      estimateHours: null,
      loggedMinutes: 0,
      createdBy: 'u2',
      createdAt: '2026-02-15T08:00:00',
      updatedAt: '2026-02-15T08:00:00',
    },
    {
      id: 'pt4',
      projectId: 'p1',
      title: 'Pruebas de usabilidad',
      description: 'Sesiones con 8 usuarios.',
      status: 'todo',
      priority: 'media',
      assigneeIds: ['u5'],
      startDate: '2026-03-01',
      dueDate: '2026-03-20',
      completedAt: null,
      position: 3,
      kanbanColumn: 'todo',
      boardCardId: null,
      boardId: null,
      attachments: [],
      estimateHours: null,
      loggedMinutes: 0,
      createdBy: 'u1',
      createdAt: '2026-02-01T12:00:00',
      updatedAt: '2026-02-01T12:00:00',
    },
  ],
  milestones: [
    {
      id: 'pm1',
      projectId: 'p1',
      title: 'Kickoff aprobado',
      description: 'Alcance y cronograma validados con el cliente.',
      startDate: '2026-01-10',
      dueDate: '2026-01-15',
      completed: true,
      position: 0,
      createdAt: '2026-01-10T10:00:00',
    },
    {
      id: 'pm2',
      projectId: 'p1',
      title: 'Diseño validado',
      description: 'Aprobación del sistema de diseño y prototipos.',
      startDate: '2026-02-01',
      dueDate: '2026-03-15',
      completed: false,
      position: 1,
      createdAt: '2026-01-10T10:00:00',
    },
    {
      id: 'pm3',
      projectId: 'p1',
      title: 'Entrega MVP',
      description: 'Versión funcional para pruebas beta.',
      startDate: '2026-03-15',
      dueDate: '2026-04-30',
      completed: false,
      position: 2,
      createdAt: '2026-01-10T10:00:00',
    },
  ],
  costs: [
    {
      id: 'pc0',
      projectId: 'p1',
      type: 'income',
      title: 'Anticipo cliente — Acme Corp',
      amount: 15000,
      category: 'Anticipo cliente',
      paymentMethod: 'transfer',
      reference: 'TRF-2026-0012',
      notes: 'Anticipo 33% del contrato',
      date: '2026-01-10',
      createdBy: 'u1',
      createdAt: '2026-01-10T10:00:00',
    },
    {
      id: 'pc1',
      projectId: 'p1',
      type: 'expense',
      title: 'Licencias Figma',
      amount: 1200,
      category: 'Herramientas',
      paymentMethod: 'card',
      reference: 'FIG-8821',
      notes: 'Plan anual equipo diseño',
      date: '2026-01-12',
      createdBy: 'u1',
      createdAt: '2026-01-12T10:00:00',
    },
    {
      id: 'pc2',
      projectId: 'p1',
      type: 'expense',
      title: 'Horas diseño UX',
      amount: 8500,
      category: 'Personal',
      paymentMethod: 'invoice',
      reference: 'INV-UX-014',
      notes: 'Enero 2026',
      date: '2026-02-01',
      createdBy: 'u1',
      createdAt: '2026-02-01T10:00:00',
    },
    {
      id: 'pc3',
      projectId: 'p1',
      type: 'expense',
      title: 'Investigación usuarios',
      amount: 3200,
      category: 'Servicios',
      paymentMethod: 'transfer',
      reference: 'SVC-RES-09',
      notes: '8 sesiones de usabilidad',
      date: '2026-02-10',
      createdBy: 'u2',
      createdAt: '2026-02-10T10:00:00',
    },
    {
      id: 'pc4',
      projectId: 'p1',
      type: 'income',
      title: 'Pago hito — Diseño validado',
      amount: 12000,
      category: 'Hito completado',
      paymentMethod: 'transfer',
      reference: 'TRF-2026-0045',
      notes: 'Segundo desembolso contrato',
      date: '2026-02-15',
      createdBy: 'u1',
      createdAt: '2026-02-15T14:00:00',
    },
  ],
  risks: [
    {
      id: 'pr1',
      projectId: 'p1',
      title: 'Retraso en feedback del cliente',
      description: 'El cliente tarda más de 5 días en aprobar entregables.',
      type: 'risk',
      severity: 'medium',
      probability: 'medium',
      status: 'open',
      mitigationPlan: 'Establecer SLA de 48h para revisiones y escalamiento automático.',
      ownerId: 'u1',
      createdBy: 'u1',
      createdAt: '2026-02-05T10:00:00',
      updatedAt: '2026-02-05T10:00:00',
    },
  ],
  deliverables: [
    {
      id: 'pd1',
      projectId: 'p1',
      title: 'Informe de auditoría UX',
      description: 'Documento con hallazgos y recomendaciones.',
      dueDate: '2026-01-25',
      status: 'delivered',
      completed: true,
      assigneeId: 'u3',
      milestoneId: 'pm1',
      attachments: [],
      log: [],
      createdAt: '2026-01-10T10:00:00',
    },
    {
      id: 'pd2',
      projectId: 'p1',
      title: 'Kit de componentes Figma',
      description: 'Biblioteca completa del sistema de diseño.',
      dueDate: '2026-03-01',
      status: 'in_progress',
      completed: false,
      assigneeId: 'u2',
      milestoneId: 'pm2',
      attachments: [],
      log: [],
      createdAt: '2026-01-10T10:00:00',
    },
  ],
  documents: [
    {
      id: 'pdoc1',
      projectId: 'p1',
      folderId: null,
      title: 'Alcance del proyecto',
      content: 'Documento de alcance firmado por el cliente el 10 de enero de 2026.',
      category: 'Contratos',
      attachments: [],
      createdBy: 'u1',
      createdAt: '2026-01-10T10:00:00',
      updatedAt: '2026-01-10T10:00:00',
    },
  ],
  folders: [
    {
      id: 'pf1',
      projectId: 'p1',
      parentId: null,
      name: 'Contratos',
      createdBy: 'u1',
      createdAt: '2026-01-10T10:00:00',
    },
  ],
  invites: [],
  members: [
    {
      id: 'pmb1',
      projectId: 'p1',
      userId: 'u1',
      role: 'owner',
      canViewFinance: true,
      canManageTasks: true,
      canManageTeam: true,
      joinedAt: '2026-01-10',
    },
    {
      id: 'pmb2',
      projectId: 'p1',
      userId: 'u2',
      role: 'admin',
      canViewFinance: true,
      canManageTasks: true,
      canManageTeam: false,
      joinedAt: '2026-01-10',
    },
    {
      id: 'pmb3',
      projectId: 'p1',
      userId: 'u3',
      role: 'member',
      canViewFinance: false,
      canManageTasks: true,
      canManageTeam: false,
      joinedAt: '2026-01-12',
    },
  ],
  activities: [
    {
      id: 'pa1',
      projectId: 'p1',
      userId: 'u1',
      action: 'Proyecto creado',
      details: 'Se inició el proyecto Rediseño App Móvil',
      createdAt: '2026-01-10T10:00:00',
    },
    {
      id: 'pa2',
      projectId: 'p1',
      userId: 'u3',
      action: 'Tarea completada',
      details: 'Auditoría UX actual marcada como completada',
      createdAt: '2026-01-24T16:00:00',
    },
    {
      id: 'pa3',
      projectId: 'p1',
      userId: 'u2',
      action: 'Costo registrado',
      details: 'Horas diseño UX — $8,500',
      createdAt: '2026-02-01T10:00:00',
    },
  ],
  timeEntries: [],
}
