import type { AppState } from '@/types'

export const SEED_DATA: AppState = {
  users: [
    {
      id: 'u1',
      name: 'Alula García',
      email: 'alula@quinlist.app',
      avatar: '',
      initials: 'AG',
    },
    {
      id: 'u2',
      name: 'Carlos Mendoza',
      email: 'carlos@quinlist.app',
      avatar: '',
      initials: 'CM',
    },
    {
      id: 'u3',
      name: 'María López',
      email: 'maria@quinlist.app',
      avatar: '',
      initials: 'ML',
    },
    {
      id: 'u4',
      name: 'Diego Ruiz',
      email: 'diego@quinlist.app',
      avatar: '',
      initials: 'DR',
    },
    {
      id: 'u5',
      name: 'Sofía Herrera',
      email: 'sofia@quinlist.app',
      avatar: '',
      initials: 'SH',
    },
  ],
  workspaces: [
    {
      id: 'ws1',
      name: 'Design Ops',
      slug: 'design-ops',
      icon: 'D',
      color: '#1e3a5f',
      members: [
        { userId: 'u1', role: 'owner', joinedAt: '2026-01-15' },
        { userId: 'u2', role: 'admin', joinedAt: '2026-01-20' },
        { userId: 'u3', role: 'member', joinedAt: '2026-02-01' },
        { userId: 'u4', role: 'member', joinedAt: '2026-02-05' },
        { userId: 'u5', role: 'viewer', joinedAt: '2026-02-10' },
      ],
      createdAt: '2026-01-15',
    },
    {
      id: 'ws2',
      name: 'Producto LATAM',
      slug: 'producto-latam',
      icon: 'P',
      color: '#2d6a4f',
      members: [
        { userId: 'u1', role: 'admin', joinedAt: '2026-02-01' },
        { userId: 'u2', role: 'owner', joinedAt: '2026-02-01' },
      ],
      createdAt: '2026-02-01',
    },
  ],
  boards: [
    {
      id: 'b1',
      workspaceId: 'ws1',
      title: 'Sprint Activo',
      slug: 'sprint-activo',
      description: 'Sprint de diseño Q1 2026',
      background: 'ocean',
      starred: true,
      integrations: [
        { type: 'google_calendar', enabled: true, config: {} },
        { type: 'slack', enabled: false, config: { url: '' } },
        { type: 'github', enabled: false, config: { repo: '' } },
        { type: 'ics_export', enabled: true, config: {} },
        { type: 'webhook', enabled: false, config: { url: '' } },
      ],
      labels: [
        { id: 'l1', name: 'Ilustración', color: '#f4d03f' },
        { id: 'l2', name: 'Video', color: '#5dade2' },
        { id: 'l3', name: 'UI/UX', color: '#bb8fce' },
        { id: 'l4', name: 'Urgente', color: '#e74c3c' },
        { id: 'l5', name: 'Backend', color: '#58d68d' },
      ],
      lists: [
        { id: 'list1', boardId: 'b1', title: 'Backlog', position: 0 },
        { id: 'list2', boardId: 'b1', title: 'Por hacer', position: 1 },
        { id: 'list3', boardId: 'b1', title: 'En proceso', position: 2 },
        { id: 'list4', boardId: 'b1', title: 'En revisión', position: 3 },
      ],
      createdAt: '2026-02-01',
    },
  ],
  cards: [
    {
      id: 'c1',
      listId: 'list1',
      boardId: 'b1',
      title: 'Diseñar iconografía del dashboard',
      description: 'Crear set de iconos consistentes para el panel principal.',
      completed: false,
      labelIds: ['l1', 'l3'],
      priority: 'alta',
      dueDate: '2026-02-16',
      assigneeIds: ['u2'],
      checklist: [
        { id: 'ch1', text: 'Investigar referencias', completed: true },
        { id: 'ch2', text: 'Crear bocetos', completed: false },
        { id: 'ch3', text: 'Exportar SVG', completed: false },
      ],
      comments: [
        {
          id: 'cm1',
          userId: 'u2',
          text: 'Ya tengo las referencias listas, empiezo con los bocetos mañana.',
          createdAt: '2026-02-10T10:30:00',
        },
      ],
      attachments: [],
      position: 0,
      createdAt: '2026-02-05',
      updatedAt: '2026-02-10',
      createdBy: 'u2',
      completedAt: null,
      durationSeconds: null,
      estimateHours: null,
      blocked: false,
      blockedReason: null,
    },
    {
      id: 'c2',
      listId: 'list2',
      boardId: 'b1',
      title: 'Video tutorial de onboarding',
      description: 'Grabar y editar video de bienvenida para nuevos usuarios.',
      completed: false,
      labelIds: ['l2'],
      priority: 'media',
      dueDate: '2026-02-21',
      assigneeIds: ['u3'],
      checklist: [
        { id: 'ch4', text: 'Escribir guion', completed: true },
        { id: 'ch5', text: 'Grabar pantalla', completed: false },
      ],
      comments: [],
      attachments: [],
      position: 0,
      createdAt: '2026-02-06',
      updatedAt: '2026-02-08',
      createdBy: 'u3',
      completedAt: null,
      durationSeconds: null,
      estimateHours: null,
      blocked: false,
      blockedReason: null,
    },
    {
      id: 'c3',
      listId: 'list2',
      boardId: 'b1',
      title: 'Rediseñar flujo de registro',
      description: 'Simplificar el proceso de registro para usuarios LATAM.',
      completed: false,
      labelIds: ['l3'],
      priority: 'alta',
      dueDate: '2026-02-24',
      assigneeIds: ['u1', 'u4'],
      checklist: [],
      comments: [
        {
          id: 'cm2',
          userId: 'u4',
          text: 'Propongo reducir de 5 a 3 pasos.',
          createdAt: '2026-02-11T14:00:00',
        },
        {
          id: 'cm3',
          userId: 'u1',
          text: 'De acuerdo, avancemos con esa propuesta.',
          createdAt: '2026-02-11T15:30:00',
        },
      ],
      attachments: [],
      position: 1,
      createdAt: '2026-02-07',
      updatedAt: '2026-02-11',
      createdBy: 'u1',
      completedAt: null,
      durationSeconds: null,
      estimateHours: null,
      blocked: false,
      blockedReason: null,
    },
    {
      id: 'c4',
      listId: 'list3',
      boardId: 'b1',
      title: 'Prototipo de tarjetas Kanban',
      description: 'Implementar componente de tarjeta con drag & drop.',
      completed: false,
      labelIds: ['l3', 'l5'],
      priority: 'alta',
      dueDate: '2026-02-18',
      assigneeIds: ['u1'],
      checklist: [
        { id: 'ch6', text: 'Diseño visual', completed: true },
        { id: 'ch7', text: 'Implementación', completed: true },
        { id: 'ch8', text: 'Pruebas', completed: false },
      ],
      comments: [],
      attachments: [],
      position: 0,
      createdAt: '2026-02-08',
      updatedAt: '2026-02-12',
      createdBy: 'u1',
      completedAt: null,
      durationSeconds: null,
      estimateHours: null,
      blocked: false,
      blockedReason: null,
    },
    {
      id: 'c5',
      listId: 'list3',
      boardId: 'b1',
      title: 'Sistema de notificaciones',
      description: 'Notificaciones en tiempo real para asignaciones y comentarios.',
      completed: false,
      labelIds: ['l5'],
      priority: 'media',
      dueDate: '2026-02-24',
      assigneeIds: ['u2'],
      checklist: [],
      comments: [],
      attachments: [],
      position: 1,
      createdAt: '2026-02-09',
      updatedAt: '2026-02-09',
      createdBy: 'u2',
      completedAt: null,
      durationSeconds: null,
      estimateHours: null,
      blocked: false,
      blockedReason: null,
    },
    {
      id: 'c6',
      listId: 'list3',
      boardId: 'b1',
      title: 'Paleta de colores QuinList',
      description: 'Definir colores de marca para la identidad visual.',
      completed: true,
      labelIds: ['l1', 'l3'],
      priority: 'baja',
      dueDate: null,
      assigneeIds: ['u3'],
      checklist: [
        { id: 'ch9', text: 'Investigar competencia', completed: true },
        { id: 'ch10', text: 'Presentar propuesta', completed: true },
      ],
      comments: [],
      attachments: [],
      position: 0,
      createdAt: '2026-01-20',
      updatedAt: '2026-02-01',
      createdBy: 'u3',
      completedAt: '2026-02-01T18:00:00',
      durationSeconds: 1036800,
      estimateHours: null,
      blocked: false,
      blockedReason: null,
    },
  ],
  notifications: [
    {
      id: 'n1',
      type: 'card_assigned',
      title: 'Nueva asignación',
      message: 'Te asignaron "Prototipo de tarjetas Kanban"',
      userId: 'u1',
      read: false,
      createdAt: '2026-02-12T09:00:00',
      metadata: { boardId: 'b1', cardId: 'c4', workspaceId: 'ws1' },
    },
    {
      id: 'n2',
      type: 'card_commented',
      title: 'Nuevo comentario',
      message: 'Diego comentó en "Rediseñar flujo de registro"',
      userId: 'u1',
      read: false,
      createdAt: '2026-02-11T14:00:00',
      metadata: { boardId: 'b1', cardId: 'c3', workspaceId: 'ws1' },
    },
    {
      id: 'n3',
      type: 'card_due_soon',
      title: 'Fecha límite próxima',
      message: '"Diseñar iconografía del dashboard" vence el 16 feb',
      userId: 'u1',
      read: true,
      createdAt: '2026-02-14T08:00:00',
      metadata: { boardId: 'b1', cardId: 'c1', workspaceId: 'ws1' },
    },
  ],
}
